# Generated by Django 4.2.4 on 2023-08-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='event',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
